### ISSUE TITLE
event listener tripping?

### ISSUE THREAD

**Issue by jonasalmeida** [episphere/sherlockWSI#1]
This a great beginning Praful, right on target for the lightweight approach :-) ! 

Minor issues - sometimes the image tiles don't load. The effect is corrected as the interaction proceeds but looking at the console it looks like there may be some tripping between async calls:

![Screenshot 2023-06-20 at 9 07 06 AM](https://github.com/episphere/sherlockWSI/assets/204769/6ecee0a5-98c7-41c5-aaec-d5fb58a687ac)

ok, so I ran some tests jumping between positions and zooming levels and I think I know what the hiccup is: at higher resolutions, openseadragon is being asked to retrieve all the tiles in the path between positions in the order it finds them. Is there an option in the renderer to queue the tiles in the reverse order (by popping the latest calls ahead of older ones)?

**Comment by PrafulB** [comment]
Solved with [commit 0e28137fe642cab5693f364c2d53a3ebc5dea177](https://github.com/episphere/sherlockWSI/commit/0e28137fe642cab5693f364c2d53a3ebc5dea177).
